### ISSUE TITLE
Potential leftover debug code

### ISSUE THREAD

**Issue by gtpho** [imagekit-developer/imagekit-go#1]
Not sure if it's intended but the current time is being logged when using signed URLs.

https://github.com/imagekit-developer/imagekit-go/blob/6d3eb2714166e5ee90036b03a9aaa703266a9e53/url.go#L81

**Comment by imagekitio** [comment]
Thank you. It's not intended and we will remove it in the next release.

**Comment by imagekitio** [comment]
Fixed in 1.0.1
