### ISSUE TITLE
Typo of environment variable within README.md

### ISSUE THREAD

**Issue by J-Tapio** [imagekit-developer/imagekit-go#2]
There seems to be a typo within README.md:

```go
// Using environment variables IMAGEKIT_PRIVATE_KEY, IMAGEKIT_PUBLIC_KEY and IMAGEKIT_URL_ENDPOINT
ik, err := ImageKit.New()
```

All worked after changing env variable from `IMAGEKIT_URL_ENDPOINT` to `IMAGEKIT_ENDPOINT_URL` after reading carefully the error message "IMAGEKIT_ENDPOINT_URL envvar not set".

Also, I think it would be great addition to include initialization code snippet to [Developer options](https://imagekit.io/dashboard/developer/api-keys) within Imagekit.io.  - Seems to be missing from there :)

**Comment by imagekitio** [comment]
Thank you. Readme updated. Soon we will update code snippets in dashboard
